language: node_js
node_js:
  - "node"

os:
  - linux

cache:
  directories:
    - "node_modules"

script:
  - "npm run test-ci"
  - "npm run lint"

before_install:
  # Recompile modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"


after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
